Add controllers
zykininho/java-shareit pull request #1
Opened 2023-04-02 12:36 UTC by zykininho

2023-04-02 15:44 UTC, andrew-larkin requested changes
Привет! Очень хороший старт, остается внести несколько корректировок и работа будет готова.

2023-04-02 15:44 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    long id;
модификаторы доступа

2023-04-02 15:44 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    long id;
модификаторы доступа

2023-04-02 15:44 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto add(@RequestHeader(value = "X-Sharer-User-Id", defaultValue = "0") long userId,
Давай для этого приложения добавим новый класс-обертку для методов контроллера ResponseEntity - он возвращает не только json, но и http-статус, что довольно удобно. Будет выглядеть как-то так:
return ResponseEntity.ok().body(itemService.addNewItem(userId, itemDto)); 
Для всех методов во всех контроллерах стоит его добавить

2023-04-02 15:44 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    long id;
модификаторы доступа

2023-04-02 15:44 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public class ItemMapper {
для этого приложения также давай добавим библиотеку mapStruct - она используется на всех реальных проектах, будет очень полезно ее изучить

2023-04-02 15:44 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    long id;
модификаторы доступа

2023-04-02 15:44 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    long id;
модификаторы доступа

2023-04-02 15:44 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    long id;
модификаторы доступа

2023-04-02 15:44 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    long id;
модификаторы доступа

2023-04-02 15:44 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    long id;
модификаторы доступа

2023-04-03 17:38 UTC, zykininho commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public class ItemMapper {
Спасибо за предложение новых библиотек!
Изучил теорию на [](https://www.baeldung.com/mapstruct)

2023-04-03 17:40 UTC, zykininho commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    long id;
Извиняюсь за "детские" ошибки

2023-04-04 17:36 UTC, closed without merging